spring.application.name=backend

spring.h2.console.enabled = true
spring.datasource.url = jdbc:h2:mem:my-string


event.image = images/

spring.app.jwtSecret=MySuperLongSecretKeyThatIsAtLeast32CharactersLong12345
spring.app.jwtExpirationMs = 300000000
spring.app.jwtCookieName = ecomCookie

