spring.application.name=backend


spring.datasource.url=jdbc:mysql://localhost:8030/event_platform
spring.datasource.username=root
spring.datasource.password=password


event.image = images/

spring.app.jwtSecret=MySuperLongSecretKeyThatIsAtLeast32CharactersLong12345
spring.app.jwtExpirationMs = 300000000
spring.app.jwtCookieName = ecomCookie


