spring.application.name=backend


spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=false

event.image = images/

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.app.jwtSecret=${JWT_SECRET}
spring.app.jwtExpirationMs = 300000000
spring.app.jwtCookieName = ecomCookie

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}


frontend.url=${FRONTEND_URL}
image.base.url=${IMAGE_BASE_URL}
logging.level.org.example.backend=DEBUG
stripe.secret.key=${STRIPE_SECRET_KEY}
openrouter.api.key=${OPENROUTER_API_KEY}

